// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: proto_files/user.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchServiceClient interface {
	SearchUser(ctx context.Context, in *SearchParam, opts ...grpc.CallOption) (*UserResponse, error)
	GetUserSteam(ctx context.Context, opts ...grpc.CallOption) (SearchService_GetUserSteamClient, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) SearchUser(ctx context.Context, in *SearchParam, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/services.SearchService/SearchUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetUserSteam(ctx context.Context, opts ...grpc.CallOption) (SearchService_GetUserSteamClient, error) {
	stream, err := c.cc.NewStream(ctx, &SearchService_ServiceDesc.Streams[0], "/services.SearchService/GetUserSteam", opts...)
	if err != nil {
		return nil, err
	}
	x := &searchServiceGetUserSteamClient{stream}
	return x, nil
}

type SearchService_GetUserSteamClient interface {
	Send(*UserRequest) error
	CloseAndRecv() (*UsersResponse, error)
	grpc.ClientStream
}

type searchServiceGetUserSteamClient struct {
	grpc.ClientStream
}

func (x *searchServiceGetUserSteamClient) Send(m *UserRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *searchServiceGetUserSteamClient) CloseAndRecv() (*UsersResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UsersResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations must embed UnimplementedSearchServiceServer
// for forward compatibility
type SearchServiceServer interface {
	SearchUser(context.Context, *SearchParam) (*UserResponse, error)
	GetUserSteam(SearchService_GetUserSteamServer) error
	mustEmbedUnimplementedSearchServiceServer()
}

// UnimplementedSearchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSearchServiceServer struct {
}

func (UnimplementedSearchServiceServer) SearchUser(context.Context, *SearchParam) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUser not implemented")
}
func (UnimplementedSearchServiceServer) GetUserSteam(SearchService_GetUserSteamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetUserSteam not implemented")
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_SearchUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.SearchService/SearchUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchUser(ctx, req.(*SearchParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetUserSteam_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SearchServiceServer).GetUserSteam(&searchServiceGetUserSteamServer{stream})
}

type SearchService_GetUserSteamServer interface {
	SendAndClose(*UsersResponse) error
	Recv() (*UserRequest, error)
	grpc.ServerStream
}

type searchServiceGetUserSteamServer struct {
	grpc.ServerStream
}

func (x *searchServiceGetUserSteamServer) SendAndClose(m *UsersResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *searchServiceGetUserSteamServer) Recv() (*UserRequest, error) {
	m := new(UserRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchUser",
			Handler:    _SearchService_SearchUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetUserSteam",
			Handler:       _SearchService_GetUserSteam_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto_files/user.proto",
}
