// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: proto_files/user.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserResponse_Hobby int32

const (
	UserResponse_Game       UserResponse_Hobby = 0
	UserResponse_Basketball UserResponse_Hobby = 1
	UserResponse_Football   UserResponse_Hobby = 2
)

// Enum value maps for UserResponse_Hobby.
var (
	UserResponse_Hobby_name = map[int32]string{
		0: "Game",
		1: "Basketball",
		2: "Football",
	}
	UserResponse_Hobby_value = map[string]int32{
		"Game":       0,
		"Basketball": 1,
		"Football":   2,
	}
)

func (x UserResponse_Hobby) Enum() *UserResponse_Hobby {
	p := new(UserResponse_Hobby)
	*p = x
	return p
}

func (x UserResponse_Hobby) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserResponse_Hobby) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_files_user_proto_enumTypes[0].Descriptor()
}

func (UserResponse_Hobby) Type() protoreflect.EnumType {
	return &file_proto_files_user_proto_enumTypes[0]
}

func (x UserResponse_Hobby) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserResponse_Hobby.Descriptor instead.
func (UserResponse_Hobby) EnumDescriptor() ([]byte, []int) {
	return file_proto_files_user_proto_rawDescGZIP(), []int{1, 0}
}

type SearchParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string  `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email    string  `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	RoleId   []int64 `protobuf:"varint,3,rep,packed,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *SearchParam) Reset() {
	*x = SearchParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchParam) ProtoMessage() {}

func (x *SearchParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchParam.ProtoReflect.Descriptor instead.
func (*SearchParam) Descriptor() ([]byte, []int) {
	return file_proto_files_user_proto_rawDescGZIP(), []int{0}
}

func (x *SearchParam) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SearchParam) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SearchParam) GetRoleId() []int64 {
	if x != nil {
		return x.RoleId
	}
	return nil
}

type UserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string             `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email    string             `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Age      *int64             `protobuf:"varint,3,opt,name=age,proto3,oneof" json:"age,omitempty"`
	RoleId   []int64            `protobuf:"varint,4,rep,packed,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Hobby    UserResponse_Hobby `protobuf:"varint,5,opt,name=hobby,proto3,enum=services.UserResponse_Hobby" json:"hobby,omitempty"`
	Role     []*Role            `protobuf:"bytes,6,rep,name=role,proto3" json:"role,omitempty"`
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetAge() int64 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *UserResponse) GetRoleId() []int64 {
	if x != nil {
		return x.RoleId
	}
	return nil
}

func (x *UserResponse) GetHobby() UserResponse_Hobby {
	if x != nil {
		return x.Hobby
	}
	return UserResponse_Game
}

func (x *UserResponse) GetRole() []*Role {
	if x != nil {
		return x.Role
	}
	return nil
}

var File_proto_files_user_proto protoreflect.FileDescriptor

var file_proto_files_user_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x1a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f,
	0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x0b, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f,
	0x6c, 0x65, 0x49, 0x64, 0x22, 0x81, 0x02, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x15, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x03, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x05, 0x68, 0x6f, 0x62, 0x62, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x48,
	0x6f, 0x62, 0x62, 0x79, 0x52, 0x05, 0x68, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x22, 0x0a, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22,
	0x2f, 0x0a, 0x05, 0x48, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65,
	0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x62, 0x61, 0x6c, 0x6c,
	0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x6f, 0x6f, 0x74, 0x62, 0x61, 0x6c, 0x6c, 0x10, 0x02,
	0x42, 0x06, 0x0a, 0x04, 0x5f, 0x61, 0x67, 0x65, 0x32, 0x4c, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x16,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2e, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_files_user_proto_rawDescOnce sync.Once
	file_proto_files_user_proto_rawDescData = file_proto_files_user_proto_rawDesc
)

func file_proto_files_user_proto_rawDescGZIP() []byte {
	file_proto_files_user_proto_rawDescOnce.Do(func() {
		file_proto_files_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_files_user_proto_rawDescData)
	})
	return file_proto_files_user_proto_rawDescData
}

var file_proto_files_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_files_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_files_user_proto_goTypes = []interface{}{
	(UserResponse_Hobby)(0), // 0: services.UserResponse.Hobby
	(*SearchParam)(nil),     // 1: services.SearchParam
	(*UserResponse)(nil),    // 2: services.UserResponse
	(*Role)(nil),            // 3: services.Role
}
var file_proto_files_user_proto_depIdxs = []int32{
	0, // 0: services.UserResponse.hobby:type_name -> services.UserResponse.Hobby
	3, // 1: services.UserResponse.role:type_name -> services.Role
	1, // 2: services.SearchService.SearchUser:input_type -> services.SearchParam
	2, // 3: services.SearchService.SearchUser:output_type -> services.UserResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_files_user_proto_init() }
func file_proto_files_user_proto_init() {
	if File_proto_files_user_proto != nil {
		return
	}
	file_proto_files_role_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_files_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_files_user_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_files_user_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_files_user_proto_goTypes,
		DependencyIndexes: file_proto_files_user_proto_depIdxs,
		EnumInfos:         file_proto_files_user_proto_enumTypes,
		MessageInfos:      file_proto_files_user_proto_msgTypes,
	}.Build()
	File_proto_files_user_proto = out.File
	file_proto_files_user_proto_rawDesc = nil
	file_proto_files_user_proto_goTypes = nil
	file_proto_files_user_proto_depIdxs = nil
}
